# Generated by Django 3.2.9 on 2021-11-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagem/'),
        ),
    ]
